import "../styles/globals.css";
import Nav from "@/components/Nav";

export const metadata = {
  title: "Leerhuis_nextjs_2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <div className="main"></div> */}

        <main className="app">
          <Nav />
          {children}
        </main>
      </body>
    </html>
  );
}
